server:
  port: 8081
spring:
  application:
    name: ich-user-provider

# 可在第3步补充 datasource/mybatis

dubbo:
  application:
    name: ich-user-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.hyang.ich.user

logging:
  level:
    root: info


