server:
  port: 8091
  tomcat:
    max-http-form-content-size: 52428800
    max-swallow-size: 52428800
spring:
  application:
    name: ich-admin-web
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

dubbo:
  application:
    name: ich-admin-web
    qos-enable: false
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    check: false
  protocol:
    name: dubbo
    payload: 52428800

logging:
  level:
    root: info


