server:
  port: 8090
spring:
  application:
    name: ich-user-web
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

dubbo:
  application:
    name: ich-user-web
    qos-enable: false
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    check: false

logging:
  level:
    root: info


