server:
  port: 8082
spring:
  application:
    name: ich-content-provider

# 可在第3步补充 datasource/mybatis

dubbo:
  application:
    name: ich-content-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20882
  scan:
    base-packages: com.hyang.ich.content

logging:
  level:
    root: info


